exclude: ["Rakefile", "tmp"]
baseurl: /doc
arvados_api_host: qr1hi.arvadosapi.com
navbar:
  userguide:
    - Getting Started
    - Tutorials
    - Examples
    - Reference
  api:
    - Concepts
    - API Methods
    - Schema
