exclude: ["Rakefile", "tmp"]
baseurl: /doc
arvados_api_host: qr1hi.arvadosapi.com
layout: default
navbar:
  userguide:
    - Getting Started
    - Tutorials
    - Examples
    - Reference
  api:
    - Concepts
    - API Methods
    - Schema
  sdk:
    - Python
