# Do not use this file for site configuration. Create application.yml
# instead (see application.yml.example).

development:
  cache_classes: false
  eager_load: true
  consider_all_requests_local: true
  action_controller.perform_caching: false
  action_mailer.raise_delivery_errors: false
  active_support.deprecation: :log
  action_dispatch.best_standards_support: :builtin
  assets.debug: true
  profiling_enabled: true
  site_name: Arvados Workbench (dev)

production:
  force_ssl: true
  cache_classes: true
  eager_load: true
  consider_all_requests_local: false
  action_controller.perform_caching: true
  serve_static_assets: false
  assets.compile: false
  assets.digest: true
  i18n.fallbacks: true
  active_support.deprecation: :notify
  profiling_enabled: false

  arvados_insecure_https: false

  data_import_dir: /data/arvados-workbench-upload/data
  data_export_dir: /data/arvados-workbench-download/data

  site_name: Arvados Workbench

test:
  cache_classes: true
  eager_load: false
  serve_static_assets: true
  static_cache_control: public, max-age=3600
  consider_all_requests_local: true
  action_controller.perform_caching: false
  action_dispatch.show_exceptions: false
  action_controller.allow_forgery_protection: false
  action_mailer.delivery_method: :test
  active_support.deprecation: :stderr
  profiling_enabled: false
  secret_token: <%= rand(2**256).to_s(36) %>
  secret_key_base: <%= rand(2**256).to_s(36) %>

  # When you run the Workbench's integration tests, it starts the API
  # server as a dependency.  These settings should match the API
  # server's Rails defaults.  If you adjust those, change these
  # settings in application.yml to match.
  arvados_login_base: https://localhost:3001/login
  arvados_v1_base: https://localhost:3001/arvados/v1
  arvados_insecure_https: true

  site_name: Workbench:test

common:
  assets.js_compressor: false
  assets.css_compressor: false
  data_import_dir: /tmp/arvados-workbench-upload
  data_export_dir: /tmp/arvados-workbench-download
  arvados_login_base: https://arvados.local/login
  arvados_v1_base: https://arvados.local/arvados/v1
  arvados_insecure_https: true
  activation_contact_link: mailto:info@arvados.org
  arvados_docsite: http://doc.arvados.org
  arvados_theme: default
  show_user_agreement_inline: false
  secret_token: ~
  secret_key_base: false
  default_openid_prefix: https://www.google.com/accounts/o8/id
  send_user_setup_notification_email: true

  user_profile_form_fields: false
