# Do not use this file for diagnostics testing configuration.
# Instead, create diagnostics.yml by making a copy

development:
  diagnostics_testing_active_user_token: "eu33jurqntstmwo05h1jr3eblmi961e802703y6657s8zb14r"
  diagnostics_testing_admin_user_token: false

production:
  diagnostics_testing_active_user_token: false
  diagnostics_testing_admin_user_token: false

common:
  diagnostics_testing_active_user_token: false
  diagnostics_testing_admin_user_token: false
